# Dependabot dependency version checks / updates
version: 2
updates:
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "04:30"
      timezone: "Asia/Shanghai"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "cargo"
    # This will update the Cargo.lock
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "04:30"
      timezone: "Asia/Shanghai"
    commit-message:
      prefix: "chore"
      include: "scope"
